#!/bin/bash

REPO=$1

mkdir -p $REPO && (cd $REPO && git init && git config receive.denycurrentbranch ignore)
echo -e "\
#!/bin/bash

WORKDIR=\$(cd -P -- \"\$(dirname -- \"\$0\")\" && pwd -P)
REPO=\$(cd \$WORKDIR && cd ../../ && pwd -P)
(cd \$REPO && unset GIT_DIR && GIT_WORK_TREE=\$REPO && git checkout -f)
" > $REPO/.git/hooks/post-receive

chmod +x $REPO/.git/hooks/post-receive
echo git remote add deploy ssh://core@localhost:$(realpath $REPO)