#!/bin/bash

REPO=$1

mkdir -p $REPO && (cd $REPO && git init && git config receive.denycurrentbranch ignore)
echo -e "\
#!/bin/bash

WORKDIR=\$(cd -P -- \"\$(dirname -- \"\$0\")\" && pwd -P)
PARENT=\$(cd \$WORKDIR && cd ../../ && pwd -P)
PROJECT=\$PARENT/$REPO

echo $PROJECT

GIT_WORK_TREE=$PROJECT git checkout -f

" > $REPO/hooks/post-receive

chmod +x $REPO/.git/hooks/post-receive
echo git remote add deploy ssh://core@localhost:22/$REPO